env: "${ENV:development}"
#服务配置
application:
  name: "min-gateway"
http-server:
  enabled: true
  server-port: "${SERVER_PORT:9080}"
log:
  enabled: true
  level: "${LOG_LEVEL:debug}"
db:
  enabled: true
  dsn: "${DB_DSN}"
cache:
  enabled: true
  dsn: "${CACHE_DSN:redis://127.0.0.1:6379/1}"
scheduled:
  enabled: true
authorization:
  dsn: "${AUTHORIZATION_DSN:redis://127.0.0.1:6379/0}"
  signature_key: "${AUTHORIZATION_SIGNATURE_KEY:}"
  ttl: ${AUTHORIZATION_TTL:7200}
  default_singleton: ${AUTHORIZATION_DEFAULT_SINGLETON:false}
gateway:
  data_path: "${GATEWAY_DATA_PATH:./data}"
  console_api:
    prefix: "${GATEWAY_CONSOLE_API_PREFIX:/_api}"
    access_token: "${GATEWAY_CONSOLE_API_ACCESS_TOKEN:}"
  native_api:
    prefix: "${GATEWAY_NATIVE_API_PREFIX:/native}"
  enable_gray_instance: ${GATEWAY_ENABLE_GRAY_INSTANCE:true}
  config_refresh_interval: ${CONFIG_REFRESH_INTERVAL:30}
  global_request_timeout: ${GLOBAL_REQUEST_TIMEOUT:30}
  log:
    concurrent_lines: 100
discovery:
  enabled: ${DISCOVERY_ENABLED:false}
  nodes:
    - "${DISCOVERY_SERVER:nacos://127.0.0.1:8848/nacos}"
  namespace_id: ""
  client:
    enabled: ${DISCOVERY_CLIENT_ENABLED:false}
    heartbeat_interval: ${DISCOVERY_CLIENT_HEARTBEAT_INTERVAL:20000}
    instance_id: "${DISCOVERY_CLIENT_INSTANCE_ID:}"
